CREATE DATABASE IF NOT EXISTS devbridge;
CREATE DATABASE IF NOT EXISTS devbridge_ai;

CREATE USER IF NOT EXISTS 'ssafy'@'%' IDENTIFIED BY '1234';
GRANT ALL PRIVILEGES ON devbridge.* TO 'ssafy'@'%';

CREATE USER IF NOT EXISTS 'ssafy'@'%' IDENTIFIED BY '1234';
GRANT ALL PRIVILEGES ON devbridge_ai.* TO 'ssafy'@'%';

FLUSH PRIVILEGES;
