spring:
  application:
    name: backend
  mail:
    host: smtp.gmail.com
    port: 587
    username: choie000208@gmail.com
    password: syvl kihn rlix jmjl
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: c2VjcmV0LWtleS1mb3ItZGV2YnJpZGdlLWFpLXByb2plY3QtYXV0aGVudGljYXRpb24=
